### ISSUE TITLE
External storage is not visible on file explorer

### ISSUE THREAD

**Issue by Amankumar2010** [NovaFusion/android_kernel_samsung_arubaslim#2]
.External storage is not visible on file explorer but is being shown in gallery music player etc apps are detecting external memory

**Comment by m-chojnacki** [comment]
Go to file manager -> settings -> general -> access mode -> prompt user mode, then the SD card will be visible as /extSdCard. External storage support will be improved in the next release.

**Comment by Amankumar2010** [comment]
thanks a lot , that works
