### ISSUE TITLE
Screen Randomly Awakes

### ISSUE THREAD

**Issue by ghost** [NovaFusion/android_kernel_samsung_arubaslim#3]
I've found this bug in the latest CyanogenMod 12.1 releases: the screen randomly turns on without any notification or anything. I've been using CyanogenMod, from NovaFusion, on my S3 Mini for a while now (I'v had the 10.0 versions) and this never happened. Is it a bug or is it just my phone that went kaput?

**Comment by Amankumar2010** [comment]
this is for cm 10.0 for galaxy core,...  assusme you are posting it on the wrong place !

**Comment by m-chojnacki** [comment]
Of course you are posting it on the wrong place...

**Comment by Amankumar2010** [comment]
:+1:
