### ISSUE TITLE
Snapchat i8260

### ISSUE THREAD

**Issue by IgVelasco** [NovaFusion/android_kernel_samsung_arubaslim#4]
Snapchat dosn't let me log in, I tried everything on the support page and I did almost anything you could think like going for an old apk or beta.
![20150908162449](https://cloud.githubusercontent.com/assets/14189126/9749902/b4c6aa1c-5667-11e5-91ac-2edc8ea84b69.jpg)

Not sure if it's just me

**Comment by m-chojnacki** [comment]
Works for me on the most recent build.

![screenshot_2015-09-09-11-16-38](https://cloud.githubusercontent.com/assets/849632/9758054/5f593978-56e4-11e5-89cc-1d769dbbb6d8.png)

**Comment by IgVelasco** [comment]
I think its the gapps but im not sure :S
