### ISSUE TITLE
AAC playback is broken

### ISSUE THREAD

**Issue by IgVelasco** [NovaFusion/android_kernel_samsung_arubaslim#5]
The voice notes that you received on the phone don't play

**Comment by 112791-Ulloa** [comment]
Its working for me!

**Comment by m-chojnacki** [comment]
It's working for me too.

**Comment by IgVelasco** [comment]
Idk mine is getting this bugs that no one has aparently. I've be en trying to go back to stock unsuccessfully and getting boot loop obligated to flash cyanogenmod again, and I just don't know what to do.

**Comment by snmatias** [comment]
some voice notes doesn't work for me too

**Comment by m-chojnacki** [comment]
Notes sent from or to your device?

**Comment by snmatias** [comment]
notes sent to my device, the .aac ones don't play by wsp and some audio players apps neither. The .mp3 and .amr works good

**Comment by m-chojnacki** [comment]
Ok, it seems serious. I'm reopening the issue.

**Comment by m-chojnacki** [comment]
I confirmed the issue - AAC playback is broken, so I gotta rename the issue.

**Comment by Amankumar2010** [comment]
:+1:

**Comment by m-chojnacki** [comment]
This issue has been resolved in a new release (20150916).
Thank you for report.
