### ISSUE TITLE
Alarm Clock no Sounds

### ISSUE THREAD

**Issue by kspb** [NovaFusion/android_kernel_samsung_arubaslim#7]
After i flashed my s3 mini i with the rom from 01.09.2015 i got a error message after every boot " clock has been closed..." I deleted all files under /data/data/com.android.deskclock/databases. This fixed the error. Now my Alarm Clock makes no sound. Even if i go to settings and change them. Can you help me?

Kind regards,
klaus

**Comment by m-chojnacki** [comment]
It's not an S3 Mini bugtracker!
